package com.eduvision.observer;

import com.eduvision.model.Alert;
import com.eduvision.model.AlertSeverity;
import com.eduvision.model.AlertStatus;
import com.eduvision.model.LectureSession;
import com.eduvision.repository.AlertRepository;
import com.eduvision.repository.SessionRepository;
import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.UUID;
import org.springframework.context.event.EventListener;
import org.springframework.stereotype.Component;

@Component
public class AlertPersistenceObserver implements SentimentEventObserver {

    private final AlertRepository alertRepository;
    private final SessionRepository sessionRepository;

    public AlertPersistenceObserver(AlertRepository alertRepository, SessionRepository sessionRepository) {
        this.alertRepository = alertRepository;
        this.sessionRepository = sessionRepository;
    }

    @Override
    public void onEvent(SentimentAlertEvent event) {
        persist(event.getSessionId(), event.getSnapshotId(), "ENGAGEMENT_DROP", event.getEngagementScore());
    }

    @EventListener
    public void onSentimentAlert(SentimentAlertEvent event) {
        onEvent(event);
    }

    @EventListener
    public void onStudentAtRisk(StudentAtRiskEvent event) {
        persist(event.getSessionId(), event.getSnapshotId(), "STUDENT_AT_RISK", event.getConfidenceScore());
    }

    @EventListener
    public void onConcentrationDrop(ConcentrationDropEvent event) {
        persist(event.getSessionId(), event.getSnapshotId(), "CONCENTRATION_DROP", event.getConcentration());
    }

    private void persist(String sessionId, String snapshotId, String type, BigDecimal value) {
        if (sessionId == null) {
            return;
        }

        sessionRepository.findById(sessionId).ifPresent(session -> {
            Alert alert = new Alert();
            alert.setId(UUID.randomUUID().toString());
            alert.setSession(session);
            alert.setCourse(session.getCourse());
            alert.setStatus(AlertStatus.open);
            alert.setSeverity(resolveSeverity(value));
            alert.setTitle(type);
            alert.setMessage("Generated by emotion processing pipeline");
            alert.setThresholdValue(BigDecimal.valueOf(0.55));
            alert.setActualValue(value);
            alert.setTriggeredAt(LocalDateTime.now());
            alert.setAlertMetadata("{\"snapshotId\":\"" + (snapshotId == null ? "" : snapshotId) + "\"}");
            alertRepository.save(alert);
        });
    }

    private AlertSeverity resolveSeverity(BigDecimal value) {
        if (value == null) {
            return AlertSeverity.info;
        }
        if (value.compareTo(BigDecimal.valueOf(0.30)) < 0) {
            return AlertSeverity.critical;
        }
        if (value.compareTo(BigDecimal.valueOf(0.55)) < 0) {
            return AlertSeverity.warning;
        }
        return AlertSeverity.info;
    }
}
